# Generated by Django 2.2.2 on 2019-06-08 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Role', models.TextField()),
                ('Active', models.BooleanField()),
                ('DateJoined', models.TextField()),
                ('WorkExperience', models.IntegerField()),
                ('Location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.TextField()),
                ('ProductCategory', models.TextField()),
                ('Specifications', models.TextField()),
                ('Description', models.TextField()),
                ('SerialNumber', models.TextField()),
                ('Price', models.FloatField()),
                ('DateCreated', models.TextField()),
                ('DateUpdated', models.TextField()),
                ('Stock', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Terminated', models.IntegerField()),
                ('IsLoanItem', models.IntegerField()),
                ('Location', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='empwithitems',
            name='EmployeeId',
        ),
        migrations.RemoveField(
            model_name='empwithitems',
            name='InventoryId',
        ),
        migrations.AddField(
            model_name='empwithitems',
            name='Employees',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='InventoryShop.Employees'),
        ),
        migrations.AddField(
            model_name='empwithitems',
            name='Inventory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='InventoryShop.Inventory'),
        ),
    ]
