# Generated by Django 2.2.2 on 2019-06-12 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryShop', '0002_auto_20190608_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='ProductImage',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='empwithitems',
            name='Inventory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='InventoryShop.Inventory'),
        ),
    ]
